🤸 mommy fully implements and documents roles~

diff --git a/src/main/sh/mommy b/src/main/sh/mommy
--- a/src/main/sh/mommy
+++ b/src/main/sh/mommy
@@ -101,37 +101,27 @@ require_not_path() {
 
 #region Config files
 # Traverses `:`-separated directories in `$1`, finds the first directory in which the file `$2` exists and is readable,
-# and stores the path to that file in `$locate_config__result`, returning 0 if and only if such a file was found.
-locate_config() {
-    locate_config__dirs="$1"
-    locate_config__dir=""
-    locate_config__result=""
+# and sources that file, returning 0 if and only if such a file was found and sourced.
+#
+# If a candidate file exists but sourcing it fails, then the whole program dies.
+load_config() {
+    load_config__dirs="$1"
+    load_config__dir=""
 
-    while [ "x$locate_config__dirs" != "x$locate_config__dir" ] ;do
-        locate_config__dir="${locate_config__dirs%%:*}"
-        locate_config__dirs="${locate_config__dirs#"$locate_config__dir":}"
+    while [ "x$load_config__dirs" != "x$load_config__dir" ]; do
+        load_config__dir="${load_config__dirs%%:*}"
+        load_config__dirs="${load_config__dirs#"$load_config__dir":}"
 
-        if [ -f "$locate_config__dir/$2" ] && [ -r "$locate_config__dir/$2" ]; then
-            locate_config__result="$locate_config__dir/$2"
+        if [ -f "$load_config__dir/$2" ] && [ -r "$load_config__dir/$2" ]; then
+            # shellcheck disable=SC1090 # User-defined target
+            if ! . "$load_config__dir/$2"; then
+                die "mommy tried and failed to load config file '$load_config__dir/$2'~"
+            fi
             return 0
         fi
     done
 
     return 1
-}
-
-# If `$1` is set, and refers to a readable file, then `$1` is sourced and written to `$locate_config__result`.
-# Otherwise, if `$1` is not set, then `$locate_config__result` is sourced unconditionally.
-load_config() {
-    if [ "x" != "x$1" ]; then
-        if [ ! -f "$1" ] || [ ! -r "$1" ]; then
-            return 1
-        fi
-        locate_config__result="$1"
-    fi
-
-    # shellcheck disable=SC1090 # User-defined target
-    . "$locate_config__result"
 }
 #endregion
 
@@ -390,12 +380,11 @@ opt_target="2"
 opt_toggle=""
 opt_role=""
 opt_user_config_dir="${XDG_CONFIG_HOME:-"$HOME/.config"}"
-opt_user_config_path=""
 opt_global_config_dirs="${XDG_CONFIG_DIRS}:/etc/:/usr/local/etc/"
 
 # Config string for getopts describes only short options. Starts with ':', then one letter for each short option. Each
-# short option can be followed by ':' to indicate that it takes an argument.
-while getopts ":hve:ps:1tr:c:u:d:-:" OPT; do
+# short option can be followed by ':' to indicate that it takes an argument. The '-:' describes all long options.
+while getopts ":hve:ps:1tu:d:r:-:" OPT; do
     # Cheap workaround for long options, see https://stackoverflow.com/a/28466267
     if [ "-" = "$OPT" ]; then
         OPT="${OPTARG%%=*}"
@@ -412,10 +401,9 @@ while getopts ":hve:ps:1tr:c:u:d:-:" OPT; do
     s|status) require_arg; require_int; opt_status="$OPTARG" ;;
     1) opt_target="1" ;;
     t|toggle) opt_toggle="1" ;;
-    r|role) require_arg; require_not_path; opt_role="$OPTARG" ;;
-    c|config) opt_user_config_path="$OPTARG" ;;
     u|user-config-dir) require_arg; opt_user_config_dir="$OPTARG" ;;
     d|global-config-dirs) require_arg; opt_global_config_dirs="$OPTARG" ;;
+    r|role) require_arg; require_not_path; opt_role="$OPTARG" ;;
     :) die "mommy's last option is missing its argument~" ;;
     ?) die "mommy doesn't know option -$OPTARG~" ;;
     *) die "mommy doesn't know option --$OPT~" ;;
@@ -454,20 +442,14 @@ fi
 
 #region Load config and state
 ## Config
-if locate_config "$opt_global_config_dirs" "mommy/config.sh"; then
-    load_config
-fi
-
-if [ "x" != "x$opt_user_config_path" ]; then
-    load_config "$opt_user_config_path"
-elif locate_config "$opt_user_config_dir" "mommy/config.sh"; then
-    load_config
-fi
+load_config "$opt_global_config_dirs" "mommy/config.sh"
+load_config "$opt_user_config_dir" "mommy/config.sh"
 
 if [ "x" != "x$opt_role" ]; then
-    if locate_config "$opt_user_config_dir:$opt_global_config_dirs" "mommy/roles/$opt_role.sh"; then
-        load_config
-    else
+    load_config "$opt_global_config_dirs" "mommy/roles/$opt_role.sh"; loaded_role__1="$?"
+    load_config "$opt_user_config_dir" "mommy/roles/$opt_role.sh"; loaded_role__2="$?"
+
+    if [ "x0" != "x$loaded_role__1" ] && [ "x0" != "x$loaded_role__2" ]; then
         die "mommy does not know the role '$opt_role'~"
     fi
 fi
